name: mambav2
channels:
  - nvidia/label/cuda-12.4.0
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cuda-nvcc=12.4.99=0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.17=h35632f6_0
  - packaging=25.0=py310haa95532_0
  - pip=25.2=pyhc872135_0
  - python=3.10.18=h981015d_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - causal-conv1d==1.4.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - fonttools==4.60.0
      - fsspec==2024.6.1
      - grpcio==1.75.0
      - h5py==3.14.0
      - huggingface-hub==0.35.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - mamba-ssm==2.2.2
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - ml-collections==1.1.0
      - monai==1.5.1
      - mpmath==1.3.0
      - networkx==3.3
      - neurite==0.2
      - nibabel==5.3.2
      - ninja==1.13.0
      - numpy==2.1.2
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.2
      - pillow==11.0.0
      - protobuf==6.32.1
      - pyparsing==3.2.5
      - pystrum==0.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==68.2.2
      - simpleitk==2.5.2
      - six==1.17.0
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.20
      - tokenizers==0.22.1
      - torch==2.4.1+cu124
      - torchaudio==2.4.1+cu124
      - torchdiffeq==0.2.5
      - torchvision==0.19.1+cu124
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - voxelmorph==0.2
      - werkzeug==3.1.3
prefix: D:\Anaconda\envs\mx363\mambav2
